Enable lint in the precommit and running it separate from formatting

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -11,9 +11,8 @@ if ! git diff --quiet; then
   exit 1
 fi
 
-# TODO: enable this once we're lint clean
-# echo "🔍 Running npm run lint..."
-# npm run lint || { echo "❌ Linting failed. Please fix errors before committing."; exit 1; }
+echo "🔍 Running npm run lint..."
+npm run lint || { echo "❌ Linting failed. Please fix errors before committing."; exit 1; }
 
 echo "🧪 Running npm run test..."
 npm run test || { echo "❌ Tests failed. Please fix them before committing."; exit 1; }
